config:
    static_url: 'http://vegrev.local'
    charset:    'utf-8'

appname:  'VR'
layout:   'main'
charset:  'UTF-8'
template: 'mojo_template'
engines:
    mojo_template:
        auto_escape: 1
        namespace: 'VR::View'
        prepend: 'use Data::Dumper; use VR::View; my $token = $_[0];'
        encoding: 'UTF-8'

session: PSGI

plugins:
    Database:
        driver:   'mysql'
        database: 'testing'
        host:     '127.0.0.1'
        username: 'vegrev'
        password: 'password'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 0
#        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]

    Params::Normalization:
        method: 'lowercase'
