layout:  "main"
charset: "UTF-8"
static_url: 'http://vegrev.local'

serializer: "JSON"

session: "DBI"
session_name: 'vr_session'
session_is_http_only: 1
session_options:
    dsn:      'DBI:mysql:database=testing;host=127.0.0.1;port=3306'
    table:    'session'
    user:     'vegrev'  
    password: 'password'
    
plugins:
    Database:
        driver:   'mysql'
        database: 'testing'
        host:     '127.0.0.1'
        username: 'vegrev'
        password: 'password'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 0
            mysql_enable_utf8: 1

    Passphrase:
        default: 'Bcrypt'
        Bcrypt:
            cost: 8

        MD5:
            salt: ''
