layout:  "main"
charset: "UTF-8"
static_url: 'http://vegrev.local'

serializer: "JSON"

session: "PSGI"

plugins:
    Database:
        driver:   'mysql'
        database: 'testing'
        host:     '127.0.0.1'
        username: 'vegrev'
        password: 'password'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 0
            mysql_enable_utf8: 1

