#!/bin/bash

# Simple init.d script to start/stop the VegRev appliaction on Ubuntu boxes.

### BEGIN INIT INFO
# Provides:          vegrev
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: VegRev Community
### END INIT INFO

PLACKUPBIN=/usr/local/bin/plackup
DIR=/usr/share/nginx/vegetablerevolution
SCRIPT=app.psgi
PORT=5000
USER=nginx
PIDFILE=/var/run/vegrev/vegrev.pid
STARMAN_OPTS="--workers 5 --env production"
HOST="127.0.0.1"


start() {
    echo "Starting VegRev Community Forum";

    start-stop-daemon --start --chuid $USER --chdir $DIR --pidfile=$PIDFILE \
        --exec $PLACKUPBIN -- --server Starman --listen $HOST:$PORT \
        --daemonize --pid $PIDFILE $STARMAN_OPTS --app $SCRIPT
}

stop() {
    echo "Stopping VegRev Community Forum";

    start-stop-daemon --stop --pidfile $PIDFILE
}

case "$1" in
    start)
        start;
    ;;

    stop)
        stop;
    ;;

    restart)
        stop;
        start;
    ;;
    *)
    echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
